{% set version = "1.6" %}

package:
  name: robotkernel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/robotkernel/robotkernel-{{ version }}.tar.gz
  sha256: 126cc82f46e80f4d6c598cae29364cdba5e1326b9571cf1b39518d220402a67e

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - nbrobot = robotkernel.nbreader:robot
    - nblibdoc = robotkernel.nbreader:libdoc

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
    - setuptools
  run:
    - docutils
    - ipykernel
    - ipywidgets
    - lunr
    - nbformat
    - pillow
    - pygments
    - python >={{ python_min }}
    - robotframework >=3.1,<5
    - setuptools

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - robotkernel
  commands:
    - pip check
    - cd tests
    - pytest -vv --tb=long --color=yes

about:
  home: https://pypi.org/project/robotkernel
  summary: A Jupyter kernel for interactive acceptance-test-driven development with the Robot Framework
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/robots-from-jupyter/robotkernel
  doc_url: https://robots-from-jupyter.github.io/robotkernel
  doc_source_url: https://github.com/robots-from-jupyter/robotkernel/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
