{% set name = "robotkernel" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b984b11cdd33688b3d457e93cdbaa1de5859868abb28c82aeb3b51e0afb6e05f

build:
  number: 0
  noarch: python
  entry_points:
    - nbrobot = robotkernel.nbreader:robot
    - nblibdoc = robotkernel.nbreader:libdoc
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - docutils
    - ipykernel
    - ipywidgets
    - lunr
    - nbformat
    - pillow
    - pygments
    - python >=3.6
    - robotframework >=3.1,<5
    - setuptools

test:
  source_files:
    - tests
  imports:
    - robotkernel
  commands:
    - python -m pip check
    - cd tests && pytest -vv
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/robotkernel/
  summary: A Jupyter kernel for interactive acceptance-test-driven development with the Robot Framework
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/robots-from-jupyter/robotkernel
  doc_url: https://robots-from-jupyter.github.io/robotkernel
  doc_source_url: https://github.com/robots-from-jupyter/robotkernel/tree/{{ version }}/docs

extra:
  recipe-maintainers:
    - bollwyvl
